batch_size: 128
epochs: 200
lr_min: 0.0
lr_max: 0.1
momentum: 0.9
seed: 42
out_dir: testing
dataset: cifar10
data_dir: ./cifar10-data
wandb_key: 
lr_scheduler: multistep
model_name: resnet18
activation: relu
weight_decay: 5e-4
conv_layer: soc
groups: 1
