batch_size: 128
epochs: 200
lr_min: 0
lr_max: 0.1
wandb_key: 
model_name: LipConvnet
momentum: 0.9
epsilon: 36
out_dir: robust
dataset: cifar10
data_dir: cifar10-data
init_channels: 32
activation: minmax_permuted
conv_layer: soc
groups: 4 2
seed: 42
weight_decay: 5e-4
block_size: 3
